name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies (main)
      run: |
        # Clean install to avoid optional dependency issues
        rm -rf node_modules package-lock.json
        npm install
      working-directory: ./connect

    - name: Install frontend dependencies
      run: |
        # Clean install to avoid rollup optional dependency issues
        rm -rf node_modules package-lock.json
        npm install
        # Verify rollup installation
        npx rollup --version
      working-directory: ./connect/src/frontend

    - name: Build project
      run: |
        echo "Starting build process..."
        npm run build
        echo "Build completed successfully"
      working-directory: ./connect

    - name: Check build artifacts
      run: |
        if [ ! -d "./connect/src/frontend/dist" ]; then
          echo "Build failed: dist directory not found"
          exit 1
        fi
        echo "Build successful: dist directory created"
