name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies (main)
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      working-directory: ./connect

    - name: Install frontend dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      working-directory: ./connect/src/frontend

    - name: Build project
      run: npm run build
      working-directory: ./connect

    - name: Check build artifacts
      run: |
        if [ ! -d "./connect/src/frontend/dist" ]; then
          echo "Build failed: dist directory not found"
          exit 1
        fi
        echo "Build successful: dist directory created"
